### ISSUE TITLE
aiService undefined

### ISSUE THREAD

**Issue by connordeckers** [ingig/code-narrator#8]
Hey! This project looks super promising, though I can't get it to run. It crashes with the below error:
```
Starting code-narrator
Understanding project and auto generating code-narrator.config.js
TypeError: Cannot read properties of undefined (reading 'aiService')
    at new ConfigQuestion (/home/connor/dev/*****/node_modules/code-narrator/dist/src/config/ConfigQuestion.js:13:56)
    at ConfigGenerator.generate (/home/connor/dev/*****/node_modules/code-narrator/dist/src/config/ConfigGenerator.js:17:30)
    at ConfigHelper.load (/home/connor/dev/*****/node_modules/code-narrator/dist/src/config/ConfigHelper.js:46:61)
    at App.run (/home/connor/dev/*****/node_modules/code-narrator/dist/src/App.js:27:38)
    at /home/connor/dev/*****/node_modules/code-narrator/dist/src/cli.js:15:15
```

Any thoughts? Not sure if I'm missing something or doing something wrong; just trying to follow the step-by-step and it's failing :(

**Comment by ingig** [comment]
@connordeckers you are not doing anything wrong, I did :)

New version that fixes this is up
